name: Rspec and Capybara
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: west-coast-skateparks_test
      POSTGRES_HOST: localhost
      RAILS_ENV: test
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install OS dependencies
        run: sudo apt-get install libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup the postgres database
        run: bundle exec rails db:create && bundle exec rails db:schema:load

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: assets precompile
        run: bundle exec rake assets:precompile --trace

      - name: Run the test suite
        run: bundle exec rspec

      - name: Upload Capybara screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: capybara-screenshots
          path: tmp/capybara/
